//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class abonnee_en_klant
    {
        public abonnee_en_klant()
        {
            this.order_regel = new HashSet<order_regel>();
        }
    
        public int AbonneeEnKlantId { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Telefoon_Nummer { get; set; }
    
        public virtual ICollection<order_regel> order_regel { get; set; }
    }
}
