//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public Adres()
        {
            this.Filiaals = new HashSet<Filiaal>();
        }
    
        public int AdresId { get; set; }
        public string Straat { get; set; }
        public string PostCode { get; set; }
        public string Land { get; set; }
    
        public virtual ICollection<Filiaal> Filiaals { get; set; }
    }
}
