//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorie
    {
        public categorie()
        {
            this.product = new HashSet<product>();
        }
    
        public int categorieId { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
