//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filiaal
    {
        public Filiaal()
        {
            this.personeel = new HashSet<personeel>();
        }
    
        public int FiliaalCodeId { get; set; }
        public string Naam { get; set; }
        public int AdresAdresId { get; set; }
    
        public virtual ICollection<personeel> personeel { get; set; }
        public virtual Adres Adre { get; set; }
    }
}
