//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class leveringRegels
    {
        public leveringRegels()
        {
            this.levering = new HashSet<levering>();
        }
    
        public int LeveringRegelsId { get; set; }
        public int productId { get; set; }
    
        public virtual ICollection<levering> levering { get; set; }
        public virtual product product { get; set; }
    }
}
