//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class levering
    {
        public int LeveringId { get; set; }
        public int personeelId { get; set; }
        public int leveringRegelsId { get; set; }
        public int statusId { get; set; }
        public string LeveringsCode { get; set; }
    
        public virtual personeel personeel { get; set; }
        public virtual leveringRegels leveringRegels { get; set; }
        public virtual status status { get; set; }
    }
}
