//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.betaling = new HashSet<betaling>();
            this.order_regel = new HashSet<order_regel>();
        }
    
        public int orderId { get; set; }
        public int personeelId { get; set; }
        public string OrderDatum { get; set; }
        public string LeveringsDatum { get; set; }
    
        public virtual ICollection<betaling> betaling { get; set; }
        public virtual ICollection<order_regel> order_regel { get; set; }
        public virtual personeel personeel { get; set; }
    }
}
