//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_regel
    {
        public int OrderRegelId { get; set; }
        public int orderId { get; set; }
        public int abonne_en_klantId { get; set; }
    
        public virtual order order { get; set; }
        public virtual abonnee_en_klant abonnee_en_klant { get; set; }
    }
}
