//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeel
    {
        public personeel()
        {
            this.levering = new HashSet<levering>();
            this.orders = new HashSet<order>();
        }
    
        public int PersoneelId { get; set; }
        public int filiaal_codeId { get; set; }
        public int FunctieId { get; set; }
        public string Voornaam { get; set; }
        public string Tussenvoegsel { get; set; }
        public string Achternaam { get; set; }
        public string PostCode { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<levering> levering { get; set; }
        public virtual Filiaal filiaalCode { get; set; }
        public virtual Functie Functie { get; set; }
        public virtual ICollection<order> orders { get; set; }
    }
}
