//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class prijs
    {
        public int PrijsId { get; set; }
        public int productId { get; set; }
        public string Prijs { get; set; }
    
        public virtual product product { get; set; }
    }
}
