//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWebKassa.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.levering = new HashSet<levering>();
        }
    
        public int StatusId { get; set; }
        public string True { get; set; }
        public string False { get; set; }
    
        public virtual ICollection<levering> levering { get; set; }
    }
}
